vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xilinx_vip
vlib questa_lib/msim/xpm
vlib questa_lib/msim/xil_defaultlib
vlib questa_lib/msim/microblaze_v11_0_14
vlib questa_lib/msim/microblaze_riscv_v1_0_3
vlib questa_lib/msim/lmb_v10_v3_0_14
vlib questa_lib/msim/lmb_bram_if_cntlr_v4_0_25
vlib questa_lib/msim/blk_mem_gen_v8_4_9
vlib questa_lib/msim/axi_lite_ipif_v3_0_4
vlib questa_lib/msim/mdm_riscv_v1_0_3
vlib questa_lib/msim/lib_cdc_v1_0_3
vlib questa_lib/msim/proc_sys_reset_v5_0_16
vlib questa_lib/msim/xlconstant_v1_1_9
vlib questa_lib/msim/smartconnect_v1_0
vlib questa_lib/msim/axi_infrastructure_v1_1_0
vlib questa_lib/msim/axi_register_slice_v2_1_33
vlib questa_lib/msim/axi_vip_v1_1_19
vlib questa_lib/msim/lib_pkg_v1_0_4
vlib questa_lib/msim/lib_srl_fifo_v1_0_4
vlib questa_lib/msim/axi_uartlite_v2_0_37

vmap xilinx_vip questa_lib/msim/xilinx_vip
vmap xpm questa_lib/msim/xpm
vmap xil_defaultlib questa_lib/msim/xil_defaultlib
vmap microblaze_v11_0_14 questa_lib/msim/microblaze_v11_0_14
vmap microblaze_riscv_v1_0_3 questa_lib/msim/microblaze_riscv_v1_0_3
vmap lmb_v10_v3_0_14 questa_lib/msim/lmb_v10_v3_0_14
vmap lmb_bram_if_cntlr_v4_0_25 questa_lib/msim/lmb_bram_if_cntlr_v4_0_25
vmap blk_mem_gen_v8_4_9 questa_lib/msim/blk_mem_gen_v8_4_9
vmap axi_lite_ipif_v3_0_4 questa_lib/msim/axi_lite_ipif_v3_0_4
vmap mdm_riscv_v1_0_3 questa_lib/msim/mdm_riscv_v1_0_3
vmap lib_cdc_v1_0_3 questa_lib/msim/lib_cdc_v1_0_3
vmap proc_sys_reset_v5_0_16 questa_lib/msim/proc_sys_reset_v5_0_16
vmap xlconstant_v1_1_9 questa_lib/msim/xlconstant_v1_1_9
vmap smartconnect_v1_0 questa_lib/msim/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 questa_lib/msim/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_33 questa_lib/msim/axi_register_slice_v2_1_33
vmap axi_vip_v1_1_19 questa_lib/msim/axi_vip_v1_1_19
vmap lib_pkg_v1_0_4 questa_lib/msim/lib_pkg_v1_0_4
vmap lib_srl_fifo_v1_0_4 questa_lib/msim/lib_srl_fifo_v1_0_4
vmap axi_uartlite_v2_0_37 questa_lib/msim/axi_uartlite_v2_0_37

vlog -work xilinx_vip -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93  \
"/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_clk_wiz_2/top_clk_wiz_2_clk_wiz.v" \
"../../../bd/top/ip/top_clk_wiz_2/top_clk_wiz_2.v" \

vcom -work microblaze_v11_0_14 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ipshared/a243/hdl/microblaze_v11_0_vh_rfs.vhd" \

vcom -work microblaze_riscv_v1_0_3 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ipshared/f9dd/hdl/microblaze_riscv_v1_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/top/ip/top_microblaze_riscv_0_0/sim/top_microblaze_riscv_0_0.vhd" \

vcom -work lmb_v10_v3_0_14 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ipshared/7495/hdl/lmb_v10_v3_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/top/ip/top_dlmb_v10_0/sim/top_dlmb_v10_0.vhd" \
"../../../bd/top/ip/top_ilmb_v10_0/sim/top_ilmb_v10_0.vhd" \

vcom -work lmb_bram_if_cntlr_v4_0_25 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ipshared/73e9/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/top/ip/top_dlmb_bram_if_cntlr_0/sim/top_dlmb_bram_if_cntlr_0.vhd" \
"../../../bd/top/ip/top_ilmb_bram_if_cntlr_0/sim/top_ilmb_bram_if_cntlr_0.vhd" \

vlog -work blk_mem_gen_v8_4_9 -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/5ec1/simulation/blk_mem_gen_v8_4.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_lmb_bram_0/sim/top_lmb_bram_0.v" \

vcom -work axi_lite_ipif_v3_0_4 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work mdm_riscv_v1_0_3 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ipshared/d547/hdl/mdm_riscv_v1_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/top/ip/top_mdm_1_0/sim/top_mdm_1_0.vhd" \

vcom -work lib_cdc_v1_0_3 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_16 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/top/ip/top_rst_clk_wiz_100M_1/sim/top_rst_clk_wiz_100M_1.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/sim/bd_74fb.v" \

vlog -work xlconstant_v1_1_9 -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_0/sim/bd_74fb_one_0.v" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_1/sim/bd_74fb_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/f49a/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_2/sim/bd_74fb_s00mmu_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_3/sim/bd_74fb_s00tr_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/63ed/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_4/sim/bd_74fb_s00sic_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_5/sim/bd_74fb_s00a2s_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_6/sim/bd_74fb_sarn_0.sv" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_7/sim/bd_74fb_srn_0.sv" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_8/sim/bd_74fb_sawn_0.sv" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_9/sim/bd_74fb_swn_0.sv" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_10/sim/bd_74fb_sbn_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_11/sim/bd_74fb_m00s2a_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/37bc/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_axi_smc_1/bd_0/ip/ip_12/sim/bd_74fb_m00e_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work axi_infrastructure_v1_1_0 -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_33 -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_19 -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../emperor.gen/sources_1/bd/top/ipshared/8c45/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ip/top_axi_smc_1/sim/top_axi_smc_1.v" \
"../../../bd/top/ip/top_ila_0_0/sim/top_ila_0_0.v" \

vcom -work lib_pkg_v1_0_4 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_4 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_uartlite_v2_0_37 -64 -93  \
"../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/sim/top_axi_uartlite_0_0.vhd" \
"../../../bd/top/ip/top_mmio_subsystem_0_2/src/top_dlmb_bram_if_cntlr_0/sim/top_dlmb_bram_if_cntlr_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ipshared/e98b/sim/bd_74fb_s00mmu_0.sv" \
"../../../bd/top/ipshared/e98b/sim/bd_74fb_m00s2a_0.sv" \
"../../../bd/top/ipshared/e98b/sim/bd_74fb_m00e_0.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ipshared/e98b/sim/top_axi_smc_1.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/ipshared/e98b/axi_mmio_controller/axi_mmio_controller.sv" \
"../../../bd/top/ipshared/e98b/uart/fifo.sv" \
"../../../bd/top/ipshared/e98b/gpio/gpio.sv" \
"../../../bd/top/ipshared/e98b/uart/rx_tx.sv" \
"../../../bd/top/ipshared/e98b/timer/timer.sv" \
"../../../bd/top/ipshared/e98b/uart/uart.sv" \
"../../../bd/top/ipshared/e98b/mmio_subsys.sv" \
"../../../bd/top/ip/top_mmio_subsystem_0_2/sim/top_mmio_subsystem_0_2.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/3cbc" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/f0b6/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/0127/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/ec67/hdl" "+incdir+../../../bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/814a/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/1017/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/52c0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/2276/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2" "+incdir+../../../../emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/hdl/verilog" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/bc9d" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src/smartconnect_v1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/sim/axi_infrastructure_v1_1_0" "+incdir+../../../../emperor.gen/sources_1/bd/top/ipshared/e98b/src" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/top/sim/top.v" \

vlog -work xil_defaultlib \
"glbl.v"

