# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.srcs/sources_1/ip/microblaze_riscv_0/microblaze_riscv_0.xci
# IP: The module: 'microblaze_riscv_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/ip/microblaze_riscv_0/microblaze_riscv_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_riscv_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/ip/microblaze_riscv_0/microblaze_riscv_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/ip/microblaze_riscv_0/microblaze_riscv_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.srcs/sources_1/ip/microblaze_riscv_0/microblaze_riscv_0.xci
# IP: The module: 'microblaze_riscv_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/ip/microblaze_riscv_0/microblaze_riscv_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/ip/microblaze_riscv_0/microblaze_riscv_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/ip/microblaze_riscv_0/microblaze_riscv_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_riscv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
