# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.srcs/sources_1/bd/top/ip/top_mmio_subsystem_0_2/top_mmio_subsystem_0_2.xci
# IP: The module: 'top_mmio_subsystem_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/mmio_subsystem.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.srcs/sources_1/bd/top/ip/top_mmio_subsystem_0_2/top_mmio_subsystem_0_2.xci
# IP: The module: 'top_mmio_subsystem_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/mmio_subsystem.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
