# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.srcs/sources_1/bd/top/ip/top_mmio_subsystem_0_2/top_mmio_subsystem_0_2.xci
# IP: The module: 'top_mmio_subsystem_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/top_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_dlmb_v10_0/top_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_v10_0 || ORIG_REF_NAME==top_dlmb_v10_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ilmb_v10_0/top_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_v10_0 || ORIG_REF_NAME==top_ilmb_v10_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_lmb_bram_0/top_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_lmb_bram_0 || ORIG_REF_NAME==top_lmb_bram_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ilmb_bram_if_cntlr_0/top_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_dlmb_bram_if_cntlr_0/top_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_mdm_1_0/top_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mdm_1_0 || ORIG_REF_NAME==top_mdm_1_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_rst_clk_wiz_100M_1/top_rst_clk_wiz_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_100M_1 || ORIG_REF_NAME==top_rst_clk_wiz_100M_1} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_microblaze_riscv_0_0/top_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_microblaze_riscv_0_0 || ORIG_REF_NAME==top_microblaze_riscv_0_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_0 || ORIG_REF_NAME==top_axi_uartlite_0_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2/top_clk_wiz_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_2 || ORIG_REF_NAME==top_clk_wiz_2} -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/top_ila_0_0_ooc.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_lmb_bram_0/top_lmb_bram_0_ooc.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_mdm_1_0/top_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_mdm_1_0 || ORIG_REF_NAME==top_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_mdm_1_0/top_mdm_1_0_ooc_trace.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_rst_clk_wiz_100M_1/top_rst_clk_wiz_100M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_100M_1 || ORIG_REF_NAME==top_rst_clk_wiz_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_rst_clk_wiz_100M_1/top_rst_clk_wiz_100M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_100M_1 || ORIG_REF_NAME==top_rst_clk_wiz_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_microblaze_riscv_0_0/top_microblaze_riscv_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_microblaze_riscv_0_0 || ORIG_REF_NAME==top_microblaze_riscv_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_microblaze_riscv_0_0/top_microblaze_riscv_0_0_ooc_debug.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/top_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_0 || ORIG_REF_NAME==top_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/top_axi_uartlite_0_0_ooc.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_0 || ORIG_REF_NAME==top_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2/top_clk_wiz_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_clk_wiz_2 || ORIG_REF_NAME==top_clk_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2/top_clk_wiz_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_clk_wiz_2 || ORIG_REF_NAME==top_clk_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2/top_clk_wiz_2_ooc.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_psr_aclk_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_s00a2s_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_sarn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_srn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_sawn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_swn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_sbn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_m00s2a_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/mmio_subsystem.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.srcs/sources_1/bd/top/ip/top_mmio_subsystem_0_2/top_mmio_subsystem_0_2.xci
# IP: The module: 'top_mmio_subsystem_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/top_ila_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_dlmb_v10_0/top_dlmb_v10_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_v10_0 || ORIG_REF_NAME==top_dlmb_v10_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ilmb_v10_0/top_ilmb_v10_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_v10_0 || ORIG_REF_NAME==top_ilmb_v10_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_lmb_bram_0/top_lmb_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_lmb_bram_0 || ORIG_REF_NAME==top_lmb_bram_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ilmb_bram_if_cntlr_0/top_ilmb_bram_if_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_dlmb_bram_if_cntlr_0/top_dlmb_bram_if_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_mdm_1_0/top_mdm_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mdm_1_0 || ORIG_REF_NAME==top_mdm_1_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_rst_clk_wiz_100M_1/top_rst_clk_wiz_100M_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_100M_1 || ORIG_REF_NAME==top_rst_clk_wiz_100M_1} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_microblaze_riscv_0_0/top_microblaze_riscv_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_microblaze_riscv_0_0 || ORIG_REF_NAME==top_microblaze_riscv_0_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_0 || ORIG_REF_NAME==top_axi_uartlite_0_0} -quiet] -quiet

# IP: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2/top_clk_wiz_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_2 || ORIG_REF_NAME==top_clk_wiz_2} -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_ila_0_0/top_ila_0_0_ooc.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_lmb_bram_0/top_lmb_bram_0_ooc.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_mdm_1_0/top_mdm_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_mdm_1_0 || ORIG_REF_NAME==top_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_mdm_1_0/top_mdm_1_0_ooc_trace.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_rst_clk_wiz_100M_1/top_rst_clk_wiz_100M_1_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_100M_1 || ORIG_REF_NAME==top_rst_clk_wiz_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_rst_clk_wiz_100M_1/top_rst_clk_wiz_100M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_100M_1 || ORIG_REF_NAME==top_rst_clk_wiz_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_microblaze_riscv_0_0/top_microblaze_riscv_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_microblaze_riscv_0_0 || ORIG_REF_NAME==top_microblaze_riscv_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_microblaze_riscv_0_0/top_microblaze_riscv_0_0_ooc_debug.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/top_axi_uartlite_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_0 || ORIG_REF_NAME==top_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/top_axi_uartlite_0_0_ooc.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_0 || ORIG_REF_NAME==top_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2/top_clk_wiz_2_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_clk_wiz_2 || ORIG_REF_NAME==top_clk_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2/top_clk_wiz_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_clk_wiz_2 || ORIG_REF_NAME==top_clk_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/top_clk_wiz_2/top_clk_wiz_2_ooc.xdc

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_psr_aclk_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_s00a2s_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_sarn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_srn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_sawn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_swn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_sbn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/bd_74fb_m00s2a_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/ip/top_mmio_subsystem_0_2/src/mmio_subsystem.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_mmio_subsystem_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
