#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definitions for peripheral MMIO_SUBSYSTEM_0 */
#define XPAR_MMIO_SUBSYSTEM_0_BASEADDR 0x46000000
#define XPAR_MMIO_SUBSYSTEM_0_HIGHADDR 0x4600ffff

/* Canonical definitions for peripheral MMIO_SUBSYSTEM_0 */
#define XPAR_MMIO_SUBSYSTEM_0_BASEADDR 0x46000000
#define XPAR_MMIO_SUBSYSTEM_0_HIGHADDR 0x4600ffff

/*  BOARD definition */
#define XPS_BOARD_AC701

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x3fff

/*  CPU parameters definition */
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_D_LMB 1
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

/* Device ID */
#define XPAR_DEVICE_ID "7a200t"

#endif  /* end of protection macro */