# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mmio_subsystem.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_2/top_clk_wiz_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_2 || ORIG_REF_NAME==top_clk_wiz_2} -quiet] -quiet

# IP: bd/top/ip/top_microblaze_riscv_0_0/top_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_microblaze_riscv_0_0 || ORIG_REF_NAME==top_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/top/ip/top_dlmb_v10_0/top_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_v10_0 || ORIG_REF_NAME==top_dlmb_v10_0} -quiet] -quiet

# IP: bd/top/ip/top_ilmb_v10_0/top_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_v10_0 || ORIG_REF_NAME==top_ilmb_v10_0} -quiet] -quiet

# IP: bd/top/ip/top_dlmb_bram_if_cntlr_0/top_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top/ip/top_ilmb_bram_if_cntlr_0/top_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top/ip/top_lmb_bram_0/top_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_lmb_bram_0 || ORIG_REF_NAME==top_lmb_bram_0} -quiet] -quiet

# IP: bd/top/ip/top_mdm_1_0/top_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mdm_1_0 || ORIG_REF_NAME==top_mdm_1_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_clk_wiz_100M_1/top_rst_clk_wiz_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_100M_1 || ORIG_REF_NAME==top_rst_clk_wiz_100M_1} -quiet] -quiet

# IP: bd/top/ip/top_ila_0_1/top_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_0_1 || ORIG_REF_NAME==top_ila_0_1} -quiet] -quiet

# IP: bd/top/ip/top_ila_1_0/top_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_1_0 || ORIG_REF_NAME==top_ila_1_0} -quiet] -quiet

# IP: bd/top/ip/top_mmio_subsystem_1_0/top_mmio_subsystem_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mmio_subsystem_1_0 || ORIG_REF_NAME==top_mmio_subsystem_1_0} -quiet] -quiet

# XDC: /home/wangjiakun/Development/emperor_soc/hardware/emperor.gen/sources_1/bd/top/top_ooc.xdc
